// Generated by sdk/scripts/gen-counter-fixtures.mjs. Do not edit.
use referee::{Envelope, Move, Outcome, Pending, Signature, SignedStep, Step, Terms};
use crate::{Action, Config, Counter};

pub const CONTEXT: felt252 = 0x1c27d35966d51336eda4383a1711053af19805f9b094e748a5dddb8ce887eee;
pub const STATE_HASH: felt252 = 0x3f10c1b86cbfefa512ef31b01ac5f78dc3426c1207c6c13e6ab3c957165c986;
pub const CHECKPOINT: felt252 = 0x3c2f0a90ef3e662cc1ef6c95618c458f445fa013beda36842b252f28b2a1ab5;
pub const RNG_LEN: u32 = 8;
pub const SEED_0: felt252 = 0x5eed0;
pub const SEED_1: felt252 = 0x5eed1;

pub fn terms() -> Terms<Config> {
    Terms {
        chain_id: 0x534e5f54455354,
        channel: 0xc4a11e1,
        game_id: 0x1,
        prover: 0xad0b7e5,
        response_seconds: 3600,
        players: array![0xa11ce, 0xb0b].span(),
        keys: array![
            0x2df1db011696a4657ca38f92c517c1bfb36e567f0a401334d5f793a0bd8a687,
            0x3c0b316d40d20edee780c640e08d0cf8239e08072fe0490a539554347fd2d15,
        ]
            .span(),
        rng_tips: array![
            0x13ba9cb3d0d93640c2ac9224c26501434310317b90e7076a395a28995a0f8bc,
            0x3568e68e657bca3dc139b2779a9b59a9258e15e0d9dbfe6bb6598396dcda461,
        ]
            .span(),
        config: Config { target: 20 },
    }
}

pub fn steps() -> Array<SignedStep<Action>> {
    array![
        SignedStep {
            step: Step { seat: 0, action: Move::Play(Action { kind: 0, amount: 3 }), entropy: 0x0 },
            signature: Signature {
                r: 0x2d7984d0eab770ae586767b40bbaa347b7eb430020fe9401bd11baeda267f2c,
                s: 0x16bccd40f097b16a7c70834432cca6076790d410dda0090b299c2d68b4e1977,
            },
        },
        SignedStep {
            step: Step {
                seat: 1,
                action: Move::Play(Action { kind: 1, amount: 0 }),
                entropy: 0x4961f5f78d6a5776d0a0787c7ac7c53ad4858fae58d59847bbf2d5a62515155,
            },
            signature: Signature {
                r: 0x2b629bbb0b7a9378e738e867a5ffbb6a603cd449e58e7b79f5b8b8f31fdde2c,
                s: 0x7fa330d39d734c718784ebc7a4e9996464883b41e57d2ccc8d50d503f093c65,
            },
        },
        SignedStep {
            step: Step {
                seat: 0,
                action: Move::Reveal(
                    0x6816196d951eb84df8af43f8cc7b82125418952b9934a12edded2b6f60e9013,
                ),
                entropy: 0x0,
            },
            signature: Signature {
                r: 0x6dff531431e91f33c9f9ce733790151719ae4f665d6113275d0a04c4d1e7d94,
                s: 0x524b999a076817e870ec65e5c441bc599b471b4ff0efbe9a04837f81fcaab32,
            },
        },
        SignedStep {
            step: Step {
                seat: 0,
                action: Move::Recommit(
                    0x3999efa3b9b0afbf5a661bf898e2d8f90bdb6bc0d8bb5f1d88eac5b51f8900f,
                ),
                entropy: 0x0,
            },
            signature: Signature {
                r: 0x208414442059401afb536fe13259805b24b8e58702c7aec34135f0e22f21aaf,
                s: 0x30f6c3e1be93d2ce9481f5d469abb95c97c559537b5579f6b147371260ba6a4,
            },
        },
        SignedStep {
            step: Step {
                seat: 0,
                action: Move::Play(Action { kind: 1, amount: 0 }),
                entropy: 0xb8aa8db35de5400be60b2a9b360b72f1cd8d8f3b8da136dc408eee7c723648,
            },
            signature: Signature {
                r: 0x3d4abc543112e6640a6634c1d853ceb48fc558dff74dfbf404b9f9bc9fb3bb0,
                s: 0x3c6bf52bbde58b6ab9b99333ae241d49ff5283dd73ca3fb271ba6c3547048b0,
            },
        },
        SignedStep {
            step: Step {
                seat: 1,
                action: Move::Reveal(
                    0x3fa78d5f72cc42e13423a147b1e62d4c1691dca4642b9bfa718540cdf60b486,
                ),
                entropy: 0x0,
            },
            signature: Signature {
                r: 0x5642ea887ba53ee31cc244094cffa9976bba9bf83d38c968f56c40ba7278898,
                s: 0x49028d7b0a6581a4636025e8162f2803f0908fd219341235fa83c3fba2ead9a,
            },
        },
        SignedStep {
            step: Step { seat: 1, action: Move::Play(Action { kind: 0, amount: 3 }), entropy: 0x0 },
            signature: Signature {
                r: 0x61b15f088a2f3a299e9b2ea6cd55a37478c43328e997c726984b6e2aed615aa,
                s: 0x14dba6fd36c5fedbbca3aa1449f7e807126bb5e9ef4d0a5044b8a4c3f7761bf,
            },
        },
        SignedStep {
            step: Step { seat: 0, action: Move::Play(Action { kind: 0, amount: 3 }), entropy: 0x0 },
            signature: Signature {
                r: 0x276f64c38e45a488fef6166ac2d2bc47485dc1ac60559cf859df41a049840ce,
                s: 0x395f5b6b6738ec53cefc024c8ae64b3649ea9ac6ca5807113cbb12fbc04c8e0,
            },
        },
        SignedStep {
            step: Step { seat: 1, action: Move::Play(Action { kind: 0, amount: 2 }), entropy: 0x0 },
            signature: Signature {
                r: 0x1d59b21045a8f980886f812207dd79c44dfd3daca7be723a10c0694585c6a3d,
                s: 0x28f176c9cca68437f4b3b0834dfe250236659315b751a561b0cbe8b759ae1ae,
            },
        },
    ]
}

pub fn expected() -> Envelope<Counter> {
    Envelope {
        seq: 9,
        transcript: 0x68afd827c2bc20825af714fb8caf9e3fb7873b6049eadcbb17584d0ffe5f2e3,
        support_turn: 6,
        last_seat: 1,
        pending: Pending { active: false, seat: 0, seq: 0, entropy: 0x0 },
        rng_heads: array![
            0xb8aa8db35de5400be60b2a9b360b72f1cd8d8f3b8da136dc408eee7c723648,
            0x3fa78d5f72cc42e13423a147b1e62d4c1691dca4642b9bfa718540cdf60b486,
        ]
            .span(),
        outcome: Outcome { finished: true, winner: 2, reason: 1 },
        game: Counter { total: 20, next: 0, gamble: false, winner: 2, target: 20 },
    }
}

pub fn acks() -> Array<Signature> {
    array![
        Signature {
            r: 0xb0bd2e444dae770198d4165eb933f0818adf608735d85a683b73f198328550,
            s: 0x24623848ca69eb285a7f1c58c63948e4bda945adb1d0bb361b11adfa4286b5b,
        },
        Signature {
            r: 0x1fb292e8ec5c00266cb837c2a6a44a6ad703adf3de054ad59de7e30e33d049b,
            s: 0x40b8d7b37934fc2bb15fdd13076b035f48d0a6c237190bc5bda29b9a0becf66,
        },
    ]
}
