// Generated by sdk/scripts/gen-counter-fixtures.mjs. Do not edit.
use referee::clocks::{Byoyomi, Standard, StandardClock, encode};
use referee::{Clock, Envelope, Move, Outcome, Pending, REFEREE, Signature, Terms, TimeControl};
use crate::hourglass::{Hourglass, HourglassClock};
use crate::{Action, Config, Counter};

pub const CONTEXT: felt252 = 0x67341a9ef52220b53215570c216a68f37cda292eac439737a2adcef538eea8;
pub const STATE_HASH: felt252 = 0x19326234109ee153327f5d10045d1f5ac36e941b7bd6fe6cbfaf88c694b6bd3;
pub const CHECKPOINT: felt252 = 0x26fc641e6e7e9900dac8df9622d4d4a6c61f85fc36af06efeb628f5ce57fffa;
/// `live_hash` at epoch 3 and deadline 12345, and `referee_resume_hash` at
/// epoch 2 from the final state.
pub const LIVE_HASH: felt252 = 0x2fb119c844444cd51303b516068b3e1bb5b32dac7855f331e4a7b66f7e8f082;
pub const REFEREE_RESUME_HASH: felt252 =
    0x29b49e732188fb6b8985cd6c17e8ae0aebb77b4f9795d2d3db75bae67ea513;
pub const RNG_LEN: u32 = 8;
pub const SEED_0: felt252 = 0x5eed0;
pub const SEED_1: felt252 = 0x5eed1;
pub const REFEREE_KEY: felt252 = 0x7e7e7e;
pub const TIMED_CONTEXT: felt252 =
    0x23f12f09f2b46051120f30c22b29f1ea440db1c414226463b16f964359102fe;
pub const TIMED_STATE_HASH: felt252 =
    0x1ae2aee380ef4ae893b6e246f230c481243fea942269a8cad1d628c50cc1b55;
pub const BYOYOMI_CONTEXT: felt252 =
    0x575e9f85b3cfcb95e6a2f2257da96eead07544019eb025b4ab6be794e8753a9;
pub const BYOYOMI_STATE_HASH: felt252 =
    0x7d62da6e0b2342d307c1dbb1ee476acf2d81c89e1bc6fd97b227d1b7ea34049;
pub const HOURGLASS_CONTEXT: felt252 =
    0x78e9895d3cc4091a05b4f3703605bfaf268e266c1176a9ba2367d7135934be0;
pub const HOURGLASS_STATE_HASH: felt252 =
    0x6c8bbd936fb9fa335fa569fa38ca28e116d6ff54e8e1105302b35d9b799e18;
/// The game that takes its randomness from the referee, whose hash chain
/// starts at `REFEREE_RNG_SEED` and has `RNG_LEN` links.
pub const REFEREE_RNG_SEED: felt252 = 0x5eed7e;
pub const ROLLED_CONTEXT: felt252 =
    0x6beb635cbbf3b423eb3ec0a41ba39b880b4684c44c0a96e536f9ea14ebff996;
pub const ROLLED_STATE_HASH: felt252 =
    0x15eaa271f70bb49d5ab9a013b0ffd68107c38f42827a0b48264c693a99c29d9;
/// `tip_hash` of that game's tip, and `void_hash` at epoch 2 from the final
/// state of the untimed game.
pub const TIP_HASH: felt252 = 0x17ee448b73b6680cbbda5eda9553bd4e2a9f1a9fc97161fb5cd7ae364a09f57;
pub const VOID_HASH: felt252 = 0x39da4629520f921cbe373d7b7d3b1556f5b6fb17639517e63fb935296c50889;
/// What seat 0's wallet signs to agree to the terms (SNIP-12, termsTypedData in the SDK).
pub const TERMS_MESSAGE: felt252 =
    0x16e6cd8d68e87df99a15d8c5f4fa5217fac0ed333d17bf061811d4c207bbb7c;

pub fn terms() -> Terms<Config> {
    Terms {
        chain_id: 0x534e5f54455354,
        channel: 0xc4a11e1,
        game_id: 0x1,
        prover: 0xad0b7e5,
        response_seconds: 3600,
        clock: Option::None,
        players: array![0xa11ce, 0xb0b].span(),
        keys: array![
            0x2df1db011696a4657ca38f92c517c1bfb36e567f0a401334d5f793a0bd8a687,
            0x3c0b316d40d20edee780c640e08d0cf8239e08072fe0490a539554347fd2d15,
        ]
            .span(),
        rng_tips: array![
            0x13ba9cb3d0d93640c2ac9224c26501434310317b90e7076a395a28995a0f8bc,
            0x3568e68e657bca3dc139b2779a9b59a9258e15e0d9dbfe6bb6598396dcda461,
        ]
            .span(),
        config: Config { target: 20 },
    }
}

pub fn steps() -> Array<Move<Action>> {
    array![
        Move::Play(Action { kind: 0, amount: 3 }),
        Move::PlayRandom(
            (
                Action { kind: 1, amount: 0 },
                0x4961f5f78d6a5776d0a0787c7ac7c53ad4858fae58d59847bbf2d5a62515155,
            ),
        ),
        Move::Reveal(0x6816196d951eb84df8af43f8cc7b82125418952b9934a12edded2b6f60e9013),
        Move::Recommit(0x3999efa3b9b0afbf5a661bf898e2d8f90bdb6bc0d8bb5f1d88eac5b51f8900f),
        Move::PlayRandom(
            (
                Action { kind: 1, amount: 0 },
                0xb8aa8db35de5400be60b2a9b360b72f1cd8d8f3b8da136dc408eee7c723648,
            ),
        ),
        Move::Reveal(0x3fa78d5f72cc42e13423a147b1e62d4c1691dca4642b9bfa718540cdf60b486),
        Move::Play(Action { kind: 0, amount: 3 }), Move::Play(Action { kind: 0, amount: 3 }),
        Move::Play(Action { kind: 0, amount: 3 }), Move::Play(Action { kind: 0, amount: 3 }),
        Move::Play(Action { kind: 0, amount: 2 }),
    ]
}

/// The seat that signed each step.
pub fn seats() -> Array<u8> {
    array![0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1]
}

/// Every step's signature. Replay takes only each seat's last one (`finals`).
pub fn signatures() -> Array<Signature> {
    array![
        Signature {
            r: 0x2e8d524df2fbdf73495a829f7612fdbaf26a1209f4f8e83f2627884d725c619,
            s: 0x21b191751f853f099a823b5bcf8e6c3f11c285f939efd3a69446d3d3167dde0,
        },
        Signature {
            r: 0x2c96f7a364111b318c0fb82768c62d6d1580e8d00e66e5d69e931590683c30,
            s: 0x728088980d30fe4d48b67bec8eeb9e980bd7a53ca004830acc5ba294a8f76aa,
        },
        Signature {
            r: 0x93ce4844e60c2b1bbee2d0aa7ba1014dce3e3e87d8a1295e527b5e83bc11d4,
            s: 0x74f9b7db7fdcb8f9cfb0e81a1ea83d770ea86f3c55f5d832d6e2a181edcf003,
        },
        Signature {
            r: 0x5d6fc07c7f0557839a1f2a00ca89fdd8ee88bc509dd20b7b6ba0e00a2f03503,
            s: 0x6eaa9dfaf8483370117ec3affdabf6b6dfc5eea46881e4a1c798d232b18670b,
        },
        Signature {
            r: 0x41f3b0697bd5d4a29fe0798658b409553fa5a7e9a397b97aa93fc7adff17916,
            s: 0x6fa46a8e6b88ee9553d501715d0f898f97c16fda18554011afe64e444a71950,
        },
        Signature {
            r: 0x30d4d9686da721f87d378459cb40c8ce8b38aa856eb763896ff0b36550bb5fc,
            s: 0x63fc76c0752a0391a684f44e1797ab01782bccc0ce3e88ab149229c403d130d,
        },
        Signature {
            r: 0xd1585b9f1e7e8d162660494627815a3f34a587c60d3353dbce515cb0f944f2,
            s: 0x166d9288d78a3b458f47bcd8a8082b2041fb90de18ac1eeb6865f5fa213265e,
        },
        Signature {
            r: 0x289e16222f0b3e15696da9386b73ae821a5e2c9867db06c23dcb576fd68bfc0,
            s: 0x2d72057063f3b2aeae40bd47f45a1e688922b1dcc11cbb92bd395d5dbc4e077,
        },
        Signature {
            r: 0x5c64ca5eb4e8543c2c4ef5056f81440af058c44933122cebafc5bc052fb8fc4,
            s: 0x7dae1d7e8b54951d1eb490a93cf7614eb6173ba609615877f692783eef02371,
        },
        Signature {
            r: 0xef5a238d9cc8d7cac1e332d355aab52370a873d859621fd736a8d9aae2e3ab,
            s: 0x2623c4ff515aa41f82b8396f2cf721f4ba70ce5905c37b5d42cc37afdb52d3b,
        },
        Signature {
            r: 0x37c4d8a672fc4b7d2762a684787b08f44e9f5b00c3530dc4183d3f343a4177d,
            s: 0x33ed0cb25eb0f7a9057d5c96c41b28426f08027ba17928fc1ab420c11cca918,
        },
    ]
}

/// Each seat's last signature among steps `from..to`, zero for a seat with none.
pub fn finals(from: u32, to: u32) -> Array<Signature> {
    finals_of(seats(), signatures(), from, to)
}

fn finals_of(
    seats: Array<u8>, signatures: Array<Signature>, from: u32, to: u32,
) -> Array<Signature> {
    let mut last = array![Signature { r: 0, s: 0 }, Signature { r: 0, s: 0 }];
    for i in from..to {
        let seat = *seats.at(i);
        last =
            if seat == REFEREE {
                last
            } else if seat == 0 {
                array![*signatures.at(i), *last.at(1)]
            } else {
                array![*last.at(0), *signatures.at(i)]
            };
    }
    last
}

pub fn expected() -> Envelope<Counter> {
    Envelope {
        seq: 11,
        transcript: 0x2113c78de4a961afae154d33862865d005d2e97c345840e6431ce96ee9c4032,
        support_turn: 8,
        last_seat: 1,
        pending: Pending { active: false, seat: 0, seq: 0, entropy: 0x0 },
        rng_heads: array![
            0xb8aa8db35de5400be60b2a9b360b72f1cd8d8f3b8da136dc408eee7c723648,
            0x3fa78d5f72cc42e13423a147b1e62d4c1691dca4642b9bfa718540cdf60b486,
        ]
            .span(),
        rng_fresh: array![false, false].span(),
        rng_referee: 0x0,
        clock: Option::None,
        outcome: Outcome { finished: true, winner: 2, reason: 1 },
        game: Counter { total: 20, next: 0, gamble: false, winner: 2, target: 20 },
    }
}

pub fn acks() -> Array<Signature> {
    array![
        Signature {
            r: 0x43ee84195040c896702bcb446478f571dbbf841c7acdbf12d320002ae11da61,
            s: 0x6434e1a2dc424b57e7119a7747262447a35176fabde95011cff79794db85b45,
        },
        Signature {
            r: 0x7743406c8f28ead8d817bb433ef92e3661a1d455ea36fb32a45d62fc7e3a11c,
            s: 0x61b3528613d492aeaef38a8be440e839c38f5520eeec951b8501ced5a2a6ad,
        },
    ]
}

pub fn timed_terms() -> Terms<Config> {
    Terms {
        chain_id: 0x534e5f54455354,
        channel: 0xc4a11e1,
        game_id: 0x2,
        prover: 0xad0b7e5,
        response_seconds: 3600,
        clock: Option::Some(
            TimeControl {
                referee: 0x6f77c2d367370dd0e65b2d4927d168eb25d33e793e2917d3eb2d7e802437929,
                settings: encode(
                    @Standard {
                        turn_ms: 30000, bank_ms: 60000, increment_ms: 2000, byoyomi: Option::None,
                    },
                ),
                rng_tip: 0x0,
            },
        ),
        players: array![0xa11ce, 0xb0b].span(),
        keys: array![
            0x2df1db011696a4657ca38f92c517c1bfb36e567f0a401334d5f793a0bd8a687,
            0x3c0b316d40d20edee780c640e08d0cf8239e08072fe0490a539554347fd2d15,
        ]
            .span(),
        rng_tips: array![
            0x13ba9cb3d0d93640c2ac9224c26501434310317b90e7076a395a28995a0f8bc,
            0x3568e68e657bca3dc139b2779a9b59a9258e15e0d9dbfe6bb6598396dcda461,
        ]
            .span(),
        config: Config { target: 20 },
    }
}

pub fn timed_steps() -> Array<Move<Action>> {
    array![
        Move::Play(Action { kind: 0, amount: 3 }),
        Move::PlayRandom(
            (
                Action { kind: 1, amount: 0 },
                0x4961f5f78d6a5776d0a0787c7ac7c53ad4858fae58d59847bbf2d5a62515155,
            ),
        ),
        Move::Reveal(0x6816196d951eb84df8af43f8cc7b82125418952b9934a12edded2b6f60e9013),
        Move::Play(Action { kind: 0, amount: 1 }), Move::Play(Action { kind: 0, amount: 1 }),
        Move::Flag,
    ]
}

/// The referee's stamp on each step.
pub fn timed_stamps() -> Array<u64> {
    array![1000000, 1040000, 1045000, 1065000, 1066000, 1160001]
}

/// The seat of each step (REFEREE for the referee's own).
pub fn timed_seats() -> Array<u8> {
    array![0, 1, 0, 0, 1, 254]
}

pub fn timed_signatures() -> Array<Signature> {
    array![
        Signature {
            r: 0x6ac88911577fc205c0d3a8a0cf6e0ce089aa1d6e3923e2c32ba378240ed9671,
            s: 0x751d1771e4007fdc2bbb3d273608b543a06a352b75e42a95912dd845d12470d,
        },
        Signature {
            r: 0x666acf4ce9e45136563c6d3822003db5dd55d055eac8a6c50d372c1d7388938,
            s: 0x122e7eb076705d57664aa55307f7f4d199de107bb698e891ac0d13515d11cfc,
        },
        Signature {
            r: 0x48958a61c836d2d2d7f56f5f80e7fc49c686e5647b1614c2b6f58f5aa6427e3,
            s: 0x632b49467146fc33744ab82da222a63156239546f649f7c5b869e7e92395376,
        },
        Signature {
            r: 0x768be567c4b4effbe3ed4e39d73b580c4ed52d15ed1e07d580f73e9ae813c8c,
            s: 0x1b2c8902431eb031a00c2d12d5bda0d80a5375fb5c006a6ddcc08de780daecd,
        },
        Signature {
            r: 0x30c99c6a3e6b1df4ea736af0b9f8b1b7350c9801f22e5064b39570d929f314d,
            s: 0x62b31520a4f9deeb89fda3fb5200d98c7c70c2c2d88fd326971af02d49a12e6,
        },
        Signature { r: 0x0, s: 0x0 },
    ]
}

/// The referee's attestation after each step.
pub fn timed_attestations() -> Array<Signature> {
    array![
        Signature {
            r: 0x52f2007f176616bd6cb2635c70d9ab377e0d5d78acd73aecc7baf8fd8a057f8,
            s: 0x7a289614046c35a4283ccfe4cd9d05481352fdf9a703ec3ba98f49e2f203590,
        },
        Signature {
            r: 0x3b4ee984b45d92bebf0aa5c04e9986d53c4d6244c588ac7994f79673c39d9d7,
            s: 0x6943176713a5dd6d94911eaf83e4ed53e4def06a2082380365f43c78a81a5e2,
        },
        Signature {
            r: 0x19b1e6e97d790018ab12007c41ac76c161d874ac06c16a60a3034dd8ee40e1f,
            s: 0x15b1a918b1f4c23838ba227489bdbfb70f50eed35359a8ef22d4b0dca8d59e8,
        },
        Signature {
            r: 0x175a0a4d6e5f015ad807862b3144803f040bd957a622c913025ef466b491423,
            s: 0x652b8aedf794f4633313d72783287d8685aa099af771c7f11a38f39c9d14ac4,
        },
        Signature {
            r: 0x1882195a5b404edebb997ebfa8dd28880da9813738d250a80fa187fc39466a0,
            s: 0x4dc6e3448a2f4a32ccb253ddb733a89b3ce3bffadbd923f8151e24477c4999a,
        },
        Signature {
            r: 0x24f70768265dd163ebee3816f7e19f450ba02150cb2b105ad0215f53516380,
            s: 0x124bf5611822f646c614203534bd8e3aea55399dff0accfe1fccc4915f7807a,
        },
    ]
}

/// Each seat's last signature among steps `from..to`.
pub fn timed_finals(from: u32, to: u32) -> Array<Signature> {
    finals_of(timed_seats(), timed_signatures(), from, to)
}

pub fn timed_expected() -> Envelope<Counter> {
    Envelope {
        seq: 6,
        transcript: 0x5eba4f37642fcfda9c6697309a4430e806c8b62a0f62f9a9ce407c57d38972d,
        support_turn: 4,
        last_seat: 1,
        pending: Pending { active: false, seat: 0, seq: 0, entropy: 0x0 },
        rng_heads: array![
            0x6816196d951eb84df8af43f8cc7b82125418952b9934a12edded2b6f60e9013,
            0x4961f5f78d6a5776d0a0787c7ac7c53ad4858fae58d59847bbf2d5a62515155,
        ]
            .span(),
        rng_fresh: array![false, false].span(),
        rng_referee: 0x0,
        clock: Option::Some(
            Clock {
                seats: encode(
                    @StandardClock { banks: array![64000, 54000].span(), periods: array![].span() },
                ),
                used: 0,
                stamp: 1160001,
                started: 1000000,
            },
        ),
        outcome: Outcome { finished: true, winner: 2, reason: 129 },
        game: Counter { total: 10, next: 0, gamble: false, winner: 0, target: 20 },
    }
}

pub fn byoyomi_terms() -> Terms<Config> {
    Terms {
        chain_id: 0x534e5f54455354,
        channel: 0xc4a11e1,
        game_id: 0x3,
        prover: 0xad0b7e5,
        response_seconds: 3600,
        clock: Option::Some(
            TimeControl {
                referee: 0x6f77c2d367370dd0e65b2d4927d168eb25d33e793e2917d3eb2d7e802437929,
                settings: encode(
                    @Standard {
                        turn_ms: 0,
                        bank_ms: 10000,
                        increment_ms: 0,
                        byoyomi: Option::Some(Byoyomi { periods: 3, period_ms: 5000 }),
                    },
                ),
                rng_tip: 0x0,
            },
        ),
        players: array![0xa11ce, 0xb0b].span(),
        keys: array![
            0x2df1db011696a4657ca38f92c517c1bfb36e567f0a401334d5f793a0bd8a687,
            0x3c0b316d40d20edee780c640e08d0cf8239e08072fe0490a539554347fd2d15,
        ]
            .span(),
        rng_tips: array![
            0x13ba9cb3d0d93640c2ac9224c26501434310317b90e7076a395a28995a0f8bc,
            0x3568e68e657bca3dc139b2779a9b59a9258e15e0d9dbfe6bb6598396dcda461,
        ]
            .span(),
        config: Config { target: 20 },
    }
}

pub fn byoyomi_steps() -> Array<Move<Action>> {
    array![
        Move::Play(Action { kind: 0, amount: 3 }), Move::Play(Action { kind: 0, amount: 3 }),
        Move::Play(Action { kind: 0, amount: 3 }),
        Move::PlayRandom(
            (
                Action { kind: 1, amount: 0 },
                0x4961f5f78d6a5776d0a0787c7ac7c53ad4858fae58d59847bbf2d5a62515155,
            ),
        ),
        Move::Reveal(0x6816196d951eb84df8af43f8cc7b82125418952b9934a12edded2b6f60e9013),
        Move::Play(Action { kind: 0, amount: 1 }), Move::Flag,
    ]
}

/// The referee's stamp on each step.
pub fn byoyomi_stamps() -> Array<u64> {
    array![1000000, 1012000, 1026000, 1032000, 1039000, 1042000, 1052001]
}

/// The seat of each step (REFEREE for the referee's own).
pub fn byoyomi_seats() -> Array<u8> {
    array![0, 1, 0, 1, 0, 0, 254]
}

pub fn byoyomi_signatures() -> Array<Signature> {
    array![
        Signature {
            r: 0x71d42e5613cc10e51bcee648c870e079358ada837657a1640943d1196cf8495,
            s: 0x5c201d4ceb7741352888bff95660b0c925dc8844f0901421a4ebeb363ba2649,
        },
        Signature {
            r: 0x71ff1775e39f41710a5030985b7795491944fc70afbed8c20caee65845fdde9,
            s: 0x30ae7209030dc34abdd29e2f31b9c8c2476e060c044cf7be6b5431fcf40173c,
        },
        Signature {
            r: 0x5c261d115d0716b6bb561c95bf71c1ab5d0d61611dc009ca5aa5c688f6bc88b,
            s: 0x19765655e2be0db6a127cfac940ce9aecbc066bf5d5cec9d390c829c9ca2460,
        },
        Signature {
            r: 0x366b62d08d3b69fffb8bd083bc71be0e6c38866ecf69addce1f9f13f21f2727,
            s: 0x643dc8000ab341dff25c07f9ba5d519703662f906f4ff7040185e8d4deda716,
        },
        Signature {
            r: 0x1d42ac17f52f3c0eaa892ce5fe96912e42d4c1e7d118577a8ff8140972fea6e,
            s: 0x5274d285c24d9fa456ffd08e15bb1253c5e7601e36a18ac4eaa5733799cdba,
        },
        Signature {
            r: 0x6d54dfabad39601fb4d10c81df4b38998fd90e35a5c12efd7a3338b26d4024b,
            s: 0x2d509b02de0bf19ec3d23e75764867a38b020148faf6738693111f10f01e76e,
        },
        Signature { r: 0x0, s: 0x0 },
    ]
}

/// The referee's attestation after each step.
pub fn byoyomi_attestations() -> Array<Signature> {
    array![
        Signature {
            r: 0x5d6acdbf233e4f274bb27938b0d4d53c623e2918085210a2831efaea42beaec,
            s: 0x566770615cf7c069a4ff3d0cff3c21dc50777f75a57fed789fe2a6f2291309,
        },
        Signature {
            r: 0x60b7786407ce72f069788d78065a2813456b7f7398fe48a7945f344e297a75f,
            s: 0xb1da3aaf1030b5693fa9d25773c5a4ba8bb14db87be269dec62e3a24166b8e,
        },
        Signature {
            r: 0x735dded34e2585d43b24a46caf892825f5f60b492dc02e7351a3010800343fe,
            s: 0x1aa18484cc9aee5dd5c6f47d463cdadcca3a36e28533fb3fcab05e514cd0056,
        },
        Signature {
            r: 0x32e8cfe49c6b9c8dc3583bf273b3153522d6b3c9d056cbc29491cedd6081da0,
            s: 0xec3b21ef3f2a33f610d5a97ec3d0b25013c90ee4f8e1069784404d83bfdfb7,
        },
        Signature {
            r: 0x26c7f1e39e1cb172902b90cb752e33957a8f0e9c0ad7b42a75a007f1cb57de6,
            s: 0x43e678b7489d9e8815eb51045699758ca396641e8a58c20998becb8c2e5614e,
        },
        Signature {
            r: 0x388981dcff070e590fb172df5e95312e3a5831a2f6852316ed2f18d83b0f564,
            s: 0x96457021629230cfdf9f5e5083687c99638090993a2f7149680f05d71ad475,
        },
        Signature {
            r: 0x3518ba3d46c223dc01be4a6b7568d74284bbc6b715492485b65be568ac5c6b8,
            s: 0x4d7d84eb5af1a48fcd99641dcf31d8fbe7c5b5297ef9921107d7d5da26089fb,
        },
    ]
}

/// Each seat's last signature among steps `from..to`.
pub fn byoyomi_finals(from: u32, to: u32) -> Array<Signature> {
    finals_of(byoyomi_seats(), byoyomi_signatures(), from, to)
}

pub fn byoyomi_expected() -> Envelope<Counter> {
    Envelope {
        seq: 7,
        transcript: 0x3ff94beb56bd4ef9ba578ee82e1669f9fe3bd362109f830f306518ecdfca0cd,
        support_turn: 5,
        last_seat: 0,
        pending: Pending { active: false, seat: 0, seq: 0, entropy: 0x0 },
        rng_heads: array![
            0x6816196d951eb84df8af43f8cc7b82125418952b9934a12edded2b6f60e9013,
            0x4961f5f78d6a5776d0a0787c7ac7c53ad4858fae58d59847bbf2d5a62515155,
        ]
            .span(),
        rng_fresh: array![false, false].span(),
        rng_referee: 0x0,
        clock: Option::Some(
            Clock {
                seats: encode(
                    @StandardClock { banks: array![0, 0].span(), periods: array![2, 2].span() },
                ),
                used: 0,
                stamp: 1052001,
                started: 1000000,
            },
        ),
        outcome: Outcome { finished: true, winner: 1, reason: 129 },
        game: Counter { total: 15, next: 1, gamble: false, winner: 0, target: 20 },
    }
}

pub fn hourglass_terms() -> Terms<Config> {
    Terms {
        chain_id: 0x534e5f54455354,
        channel: 0xc4a11e1,
        game_id: 0x4,
        prover: 0xad0b7e5,
        response_seconds: 3600,
        clock: Option::Some(
            TimeControl {
                referee: 0x6f77c2d367370dd0e65b2d4927d168eb25d33e793e2917d3eb2d7e802437929,
                settings: encode(@Hourglass { bank_ms: 10000 }),
                rng_tip: 0x0,
            },
        ),
        players: array![0xa11ce, 0xb0b].span(),
        keys: array![
            0x2df1db011696a4657ca38f92c517c1bfb36e567f0a401334d5f793a0bd8a687,
            0x3c0b316d40d20edee780c640e08d0cf8239e08072fe0490a539554347fd2d15,
        ]
            .span(),
        rng_tips: array![
            0x13ba9cb3d0d93640c2ac9224c26501434310317b90e7076a395a28995a0f8bc,
            0x3568e68e657bca3dc139b2779a9b59a9258e15e0d9dbfe6bb6598396dcda461,
        ]
            .span(),
        config: Config { target: 20 },
    }
}

pub fn hourglass_steps() -> Array<Move<Action>> {
    array![
        Move::Start, Move::Play(Action { kind: 0, amount: 3 }),
        Move::Play(Action { kind: 0, amount: 3 }), Move::Play(Action { kind: 0, amount: 3 }),
        Move::Play(Action { kind: 0, amount: 3 }), Move::Flag,
    ]
}

/// The referee's stamp on each step.
pub fn hourglass_stamps() -> Array<u64> {
    array![1000000, 1002000, 1006000, 1015000, 1016000, 1020001]
}

/// The seat of each step (REFEREE for the referee's own).
pub fn hourglass_seats() -> Array<u8> {
    array![254, 0, 1, 0, 1, 254]
}

pub fn hourglass_signatures() -> Array<Signature> {
    array![
        Signature { r: 0x0, s: 0x0 },
        Signature {
            r: 0x5cb6b124b55e2993284d7724ebc05046c23730a69864d5401cddb673fb7d66,
            s: 0x7e08342a7ec799f1596f07be0b8eddd09c488c6e1594560f5d7b651fdc1d2c7,
        },
        Signature {
            r: 0x4521efecde34f22251100ac192998cd471c14892a0967889187098aa54da8aa,
            s: 0x62c09e04c763d9425f55e357705779f3001d0d595fefddc10a6cc8e6307ae18,
        },
        Signature {
            r: 0x45bc0a67f10064c5a0b2eebf10e2d56005d3969c95932a2e5dcf8770f7c0bcb,
            s: 0x786ce80bbc183966c7da174403c12b490bd7ccc9efc883beb8e301a3d8c7e6b,
        },
        Signature {
            r: 0x67990e9dd1718b1c18f4323063dc9992d8f6aeadf1b39d0687543624e72d5db,
            s: 0x55fa6286b2aad5a8b589c1f787a337a45d4aecbc12dcddc7864825396a69a5b,
        },
        Signature { r: 0x0, s: 0x0 },
    ]
}

/// The referee's attestation after each step.
pub fn hourglass_attestations() -> Array<Signature> {
    array![
        Signature {
            r: 0x7864dd5e906f4632bf004ca35fcc4b05ba3e031dc7083b7f67489baa34cab9c,
            s: 0x438d7a7f4fda337de8e685ea7eaa86448ba1b7620885be6a0850827957dcdf3,
        },
        Signature {
            r: 0x2127d3ade1878a7ae94a23aa12318f207748e68a099125f2484a199b70c13f5,
            s: 0x693f34f9e97b31e0be329046a24d25bc7b8f93f4a593028fbcc1410ddfef177,
        },
        Signature {
            r: 0x3fb87390040e2ceeae5921b01c2a51695a11315c147c9a376c025c58dd946a1,
            s: 0x570cd2f65a3b8a705d6008392fa22d33e7a243230775e18314ee204fd88c7fe,
        },
        Signature {
            r: 0x5e1d3319a956467203fbfb160a6d1c625f67b3e365fdbc28792754797d15d57,
            s: 0x5dccefff9200b3d21d44ce9ba7abb9fb2ba43f27a3be4460964fada1c5716d5,
        },
        Signature {
            r: 0x623b836a898dbdfbbab0b65c7505487d39403ec886696b6479416a065d265fa,
            s: 0x449ca8917d1e5b6c28c574ca9bcbabca552ccd1622d89694eaa92bc29ab37e,
        },
        Signature {
            r: 0x1106b6af039ad8e5f3838982d527e2759d7e14ab6237d901d8ac7aeb0691158,
            s: 0x3eb03fbc915eb4daa2690daee34c3152ee3fad1ed7fa8c5fe99ae5738d83dc5,
        },
    ]
}

/// Each seat's last signature among steps `from..to`.
pub fn hourglass_finals(from: u32, to: u32) -> Array<Signature> {
    finals_of(hourglass_seats(), hourglass_signatures(), from, to)
}

pub fn hourglass_expected() -> Envelope<Counter> {
    Envelope {
        seq: 6,
        transcript: 0xf7b71c45a648ba58b6587886beb22ceddce3eda160362ca6555a160d48284f,
        support_turn: 4,
        last_seat: 1,
        pending: Pending { active: false, seat: 0, seq: 0, entropy: 0x0 },
        rng_heads: array![
            0x13ba9cb3d0d93640c2ac9224c26501434310317b90e7076a395a28995a0f8bc,
            0x3568e68e657bca3dc139b2779a9b59a9258e15e0d9dbfe6bb6598396dcda461,
        ]
            .span(),
        rng_fresh: array![true, true].span(),
        rng_referee: 0x0,
        clock: Option::Some(
            Clock {
                seats: encode(@HourglassClock { banks: array![4000, 16000].span() }),
                used: 0,
                stamp: 1020001,
                started: 1000000,
            },
        ),
        outcome: Outcome { finished: true, winner: 2, reason: 129 },
        game: Counter { total: 12, next: 0, gamble: false, winner: 0, target: 20 },
    }
}

pub fn rolled_terms() -> Terms<Config> {
    Terms {
        chain_id: 0x534e5f54455354,
        channel: 0xc4a11e1,
        game_id: 0x5,
        prover: 0xad0b7e5,
        response_seconds: 3600,
        clock: Option::Some(
            TimeControl {
                referee: 0x6f77c2d367370dd0e65b2d4927d168eb25d33e793e2917d3eb2d7e802437929,
                settings: encode(
                    @Standard {
                        turn_ms: 30000, bank_ms: 60000, increment_ms: 0, byoyomi: Option::None,
                    },
                ),
                rng_tip: 0x4703a6c3ec512c17158cfa1fd9a0df1a16b11c2fd3d23f628b3ea229348e69a,
            },
        ),
        players: array![0xa11ce, 0xb0b].span(),
        keys: array![
            0x2df1db011696a4657ca38f92c517c1bfb36e567f0a401334d5f793a0bd8a687,
            0x3c0b316d40d20edee780c640e08d0cf8239e08072fe0490a539554347fd2d15,
        ]
            .span(),
        rng_tips: array![
            0x13ba9cb3d0d93640c2ac9224c26501434310317b90e7076a395a28995a0f8bc,
            0x3568e68e657bca3dc139b2779a9b59a9258e15e0d9dbfe6bb6598396dcda461,
        ]
            .span(),
        config: Config { target: 20 },
    }
}

pub fn rolled_steps() -> Array<Move<Action>> {
    array![
        Move::Play(Action { kind: 0, amount: 3 }),
        Move::PlayRandom(
            (
                Action { kind: 1, amount: 0 },
                0x4961f5f78d6a5776d0a0787c7ac7c53ad4858fae58d59847bbf2d5a62515155,
            ),
        ),
        Move::Reveal(0xf4a89e71cd646b27bfe5b776a122a34a51b4ed5d501091e12ccad8e4e2674),
        Move::PlayRandom(
            (
                Action { kind: 1, amount: 0 },
                0x6816196d951eb84df8af43f8cc7b82125418952b9934a12edded2b6f60e9013,
            ),
        ),
        Move::Reveal(0x568d74f9d1788106145134ce74199889279234d4747001d319200a1665f5b4e),
        Move::Play(Action { kind: 0, amount: 1 }), Move::Flag,
    ]
}

/// The referee's stamp on each step.
pub fn rolled_stamps() -> Array<u64> {
    array![1000000, 1010000, 1010000, 1015000, 1015700, 1035700, 1125701]
}

/// The seat of each step (REFEREE for the referee's own).
pub fn rolled_seats() -> Array<u8> {
    array![0, 1, 254, 0, 254, 1, 254]
}

pub fn rolled_signatures() -> Array<Signature> {
    array![
        Signature {
            r: 0x497d7e385788d2853a9fc2f3277e9151126fe6bafc20f832f0f7844a80edab7,
            s: 0x3bbfeb2bdcd24f55b456597ea086a276eb955f28baa3ac327a82677e5620c3,
        },
        Signature {
            r: 0xcfbbdf5a20d37df112c73d40a977e96a5d99f71b2addad475f869e031fd48c,
            s: 0x64f5ccfcbe621bd496bb46b343308558f06f61012353d1011b9d459b36e4b03,
        },
        Signature { r: 0x0, s: 0x0 },
        Signature {
            r: 0x7f682f8a539d3b1c2e028711fd81f8c070b304d138cd369cb260efa5e7a4eed,
            s: 0x7bca324212f92a6a8ee8d452d634834db42dba4eb3da8b2dba5cfb36cdae88e,
        },
        Signature { r: 0x0, s: 0x0 },
        Signature {
            r: 0x7a22dc21a82ff8180863cfce5aa40020e6194cf008b996dea3efe50ada042c4,
            s: 0x729d709aa4ff41b3835d606892b9c19b0bbc7839fea34cda1374999b7e75c63,
        },
        Signature { r: 0x0, s: 0x0 },
    ]
}

/// The referee's attestation after each step.
pub fn rolled_attestations() -> Array<Signature> {
    array![
        Signature {
            r: 0x7ec60ffc31b686b75407b85adcc23ab50336aa6b9b55fd937e8fb432151e1a8,
            s: 0x67e3db3749ee14526c09ccf7960c7f9d08e5da57113166d8fa81382d7488825,
        },
        Signature {
            r: 0x773f32a5f121ebe5fbfe9328accea28f0c47ecb5a0df3559ff3a06cd15456ce,
            s: 0xa16edea59b45fe7f4728c6f6706381af26abf5d6c1ba06714b595efec9da34,
        },
        Signature {
            r: 0x1e7f91a6c73ef80545e06330fb5e9ec074b8a2e11c94b83eb2ac7a3b79e00e9,
            s: 0x4d8ae984c9646ffc5b37d8bc775587f07319e482a62dde18ed899a0abb552af,
        },
        Signature {
            r: 0x926860a85c9e582cb56912856bd77a444697f126849027b8528c29af80e9ac,
            s: 0x4f7ba642e631521b9a3c22f8c9263c82ef10fac6ef02e34d7b9977f8baaadc2,
        },
        Signature {
            r: 0x79f279f56de352c6601ac9bfae7691bd866004cdced8f970ebb08fa058f6805,
            s: 0x7155e808b5f3270b7f0c0d93364ced78312f1cac081e80016720bf1b0e4e7db,
        },
        Signature {
            r: 0x38bac930c784efc2164333c1a1feee26e54a2470fdedc8823c073fb748a926f,
            s: 0x5d025a7d961eb56d57d70188e0643f8bdc2934f343c7dde3a30eda97691602f,
        },
        Signature {
            r: 0x780a4d39ad404605618d418faef824fbd09b7c8b1882b1ef804ccf6fee29015,
            s: 0x604808b056191618dc4b5ff4e6ac942cb93232c392e002c59af6d55fdf5ba31,
        },
    ]
}

/// Each seat's last signature among steps `from..to`.
pub fn rolled_finals(from: u32, to: u32) -> Array<Signature> {
    finals_of(rolled_seats(), rolled_signatures(), from, to)
}

pub fn rolled_expected() -> Envelope<Counter> {
    Envelope {
        seq: 7,
        transcript: 0x13e79dae6eb0f1c20c174c09e5b7e926f1eaf6181d95b5e933698030a0d4bf4,
        support_turn: 4,
        last_seat: 1,
        pending: Pending { active: false, seat: 0, seq: 0, entropy: 0x0 },
        rng_heads: array![
            0x6816196d951eb84df8af43f8cc7b82125418952b9934a12edded2b6f60e9013,
            0x4961f5f78d6a5776d0a0787c7ac7c53ad4858fae58d59847bbf2d5a62515155,
        ]
            .span(),
        rng_fresh: array![false, false].span(),
        rng_referee: 0x568d74f9d1788106145134ce74199889279234d4747001d319200a1665f5b4e,
        clock: Option::Some(
            Clock {
                seats: encode(
                    @StandardClock { banks: array![60000, 60000].span(), periods: array![].span() },
                ),
                used: 0,
                stamp: 1125701,
                started: 1000000,
            },
        ),
        outcome: Outcome { finished: true, winner: 2, reason: 129 },
        game: Counter { total: 13, next: 0, gamble: false, winner: 0, target: 20 },
    }
}
