// Generated by sdk/scripts/gen-counter-fixtures.mjs. Do not edit.
use referee::clocks::{Byoyomi, Standard, StandardClock, encode};
use referee::{Clock, Envelope, Move, Outcome, Pending, REFEREE, Signature, Terms, TimeControl};
use crate::hourglass::{Hourglass, HourglassClock};
use crate::{Action, Config, Counter};

pub const CONTEXT: felt252 = 0x3692d1446de44c4fc16d0369f03ee44506dafea508adf722c391cb5a79e34b2;
pub const STATE_HASH: felt252 = 0x45c38cbe132ea3fbca01e524eea976615f0f6758177dad325b65e63e961c380;
pub const CHECKPOINT: felt252 = 0x32904dcdad4e1a394a70711211aadad0900e349266eedf0daf08f3371ed946a;
/// `live_hash` at epoch 3 and deadline 12345, and `referee_resume_hash` at
/// epoch 2 from the final state.
pub const LIVE_HASH: felt252 = 0x133e4166fe51b3c4c1ef22b4dbd57977cc40e1af4c387f75cb5f82e98480dea;
pub const REFEREE_RESUME_HASH: felt252 =
    0x1f6aeca981acdee882db5de79a34226e0738774134c9886505108b72493958a;
pub const RNG_LEN: u32 = 8;
pub const SEED_0: felt252 = 0x5eed0;
pub const SEED_1: felt252 = 0x5eed1;
pub const REFEREE_KEY: felt252 = 0x7e7e7e;
pub const TIMED_CONTEXT: felt252 =
    0x2017e23087676106cb7ba87d3c52dc3058f4d262e36e78c24c4c842a157ed90;
pub const TIMED_STATE_HASH: felt252 =
    0x7af660c45b7391072881ef72aa7ed30851f696807bba15c88e7273548300fae;
pub const BYOYOMI_CONTEXT: felt252 =
    0x2c1aa06bce65eecceed19d039a31288790751c3a696dd9a02c7f6f8d55382f4;
pub const BYOYOMI_STATE_HASH: felt252 =
    0x6d2074ef6dcfc85c1c271ed0da5be6ce0836b72f4c73a40c1fc5f681c53c0ac;
pub const HOURGLASS_CONTEXT: felt252 =
    0x22ccfbf3abd0cfc85539eaf919c68079b4b477332ea0457b84d3910fc25790e;
pub const HOURGLASS_STATE_HASH: felt252 =
    0x57904641beb5e59b6836012220c9c48497f3aafd008683ae6e050441a1ea2f;
/// The game that takes its randomness from the referee, whose hash chain
/// starts at `REFEREE_RNG_SEED` and has `RNG_LEN` links.
pub const REFEREE_RNG_SEED: felt252 = 0x5eed7e;
pub const ROLLED_CONTEXT: felt252 =
    0x64f8187b7f1e13af38b2652cf7bc4ca61fcdfa7f4c6483f35ce33890d255ae2;
pub const ROLLED_STATE_HASH: felt252 =
    0x21e9c59c670775b91d80dd2ca61eda033bf31af0619f51fa9456f9ae9ff37c3;
/// `tip_hash` of that game's tip, and `void_hash` at epoch 2 from the final
/// state of the untimed game.
pub const TIP_HASH: felt252 = 0x17ee448b73b6680cbbda5eda9553bd4e2a9f1a9fc97161fb5cd7ae364a09f57;
pub const VOID_HASH: felt252 = 0x1bfc4044db26784afac401f1a2d77fbbd92e29edab847341628673cc6a403ad;

pub fn terms() -> Terms<Config> {
    Terms {
        chain_id: 0x534e5f54455354,
        channel: 0xc4a11e1,
        game_id: 0x1,
        prover: 0xad0b7e5,
        response_seconds: 3600,
        clock: Option::None,
        players: array![0xa11ce, 0xb0b].span(),
        keys: array![
            0x2df1db011696a4657ca38f92c517c1bfb36e567f0a401334d5f793a0bd8a687,
            0x3c0b316d40d20edee780c640e08d0cf8239e08072fe0490a539554347fd2d15,
        ]
            .span(),
        rng_tips: array![
            0x13ba9cb3d0d93640c2ac9224c26501434310317b90e7076a395a28995a0f8bc,
            0x3568e68e657bca3dc139b2779a9b59a9258e15e0d9dbfe6bb6598396dcda461,
        ]
            .span(),
        config: Config { target: 20 },
    }
}

pub fn steps() -> Array<Move<Action>> {
    array![
        Move::Play(Action { kind: 0, amount: 3 }),
        Move::PlayRandom(
            (
                Action { kind: 1, amount: 0 },
                0x4961f5f78d6a5776d0a0787c7ac7c53ad4858fae58d59847bbf2d5a62515155,
            ),
        ),
        Move::Reveal(0x6816196d951eb84df8af43f8cc7b82125418952b9934a12edded2b6f60e9013),
        Move::Recommit(0x3999efa3b9b0afbf5a661bf898e2d8f90bdb6bc0d8bb5f1d88eac5b51f8900f),
        Move::PlayRandom(
            (
                Action { kind: 1, amount: 0 },
                0xb8aa8db35de5400be60b2a9b360b72f1cd8d8f3b8da136dc408eee7c723648,
            ),
        ),
        Move::Reveal(0x3fa78d5f72cc42e13423a147b1e62d4c1691dca4642b9bfa718540cdf60b486),
        Move::Play(Action { kind: 0, amount: 3 }), Move::Play(Action { kind: 0, amount: 3 }),
        Move::Play(Action { kind: 0, amount: 2 }),
    ]
}

/// The seat that signed each step.
pub fn seats() -> Array<u8> {
    array![0, 1, 0, 0, 0, 1, 1, 0, 1]
}

/// Every step's signature. Replay takes only each seat's last one (`finals`).
pub fn signatures() -> Array<Signature> {
    array![
        Signature {
            r: 0x5e34e2742f8d3fe37e04369a292176b6556e4932204590824cb2fef150fb000,
            s: 0x257c74bf681496afb8a94dafdfc0a4005d44b79cd4a4f4eb0fc0fe4253195ab,
        },
        Signature {
            r: 0x4da65e96def4d454ea3af116f51be7dded62de77caf817cfe161db4f0c595bc,
            s: 0x7af8652405953aff8f42d10ed9539c34aa970988d34df317f2a2f3a9c3839a1,
        },
        Signature {
            r: 0x4d8d8836e9b32910c7c1984740171a08705be7639e3057201f8fc6fb2b0eb6f,
            s: 0x23cdefca8db16ae154b3e8aabb7e4196b85d4f8ace689d5fc92d9c39fb0e9d8,
        },
        Signature {
            r: 0x6e5f60c91e571bb394ded1d3b8bbc2691346d473c1f74e31666bf19ccbf5f57,
            s: 0x5f70d873bc297e4a15d65811740d3670f707a36e9e59d53161f4097cf88d137,
        },
        Signature {
            r: 0x3dfabf2953ffa3a7d0ddccfaf55dedee7a2d1b489ce4118f0c56d330a510398,
            s: 0x60dbfb90232079cce861f5e60f82239473d791fd1faf135c11dcf8fab416054,
        },
        Signature {
            r: 0x17bd5534e5de6d3cee76a526ac5aafe1736d20db201f530aee7c59415c2f631,
            s: 0x79ddd340ce737b5b60f1ebe0b8de3d1433d920e79b11129a52409fd015c2edd,
        },
        Signature {
            r: 0x6ecde8a7bc913c0f70bd41c60672dcb918e13a1fa1d6d85f663c0c7ea056359,
            s: 0x2974aef61f80821d564dda91b3041d200ecb6a08983f7f334e85aadfb287af7,
        },
        Signature {
            r: 0x3eb63d3e1b9d4bb897a6afd4cc2999ac9929c83032ea6996346b8b673e6e152,
            s: 0x367a14f0e96ed445aa64813e03aff3961018a2d155b3460f8a5e6f4cefb6f0e,
        },
        Signature {
            r: 0x652c5f0c79c3aace834b4f4028de9eaeb20c5891f0f0a9f724e4e26fad1dbb4,
            s: 0x2f941b83715d5d55c9b8c6e3ac10569747588f69ecba9e39200e408b11fdb2d,
        },
    ]
}

/// Each seat's last signature among steps `from..to`, zero for a seat with none.
pub fn finals(from: u32, to: u32) -> Array<Signature> {
    finals_of(seats(), signatures(), from, to)
}

fn finals_of(
    seats: Array<u8>, signatures: Array<Signature>, from: u32, to: u32,
) -> Array<Signature> {
    let mut last = array![Signature { r: 0, s: 0 }, Signature { r: 0, s: 0 }];
    for i in from..to {
        let seat = *seats.at(i);
        last =
            if seat == REFEREE {
                last
            } else if seat == 0 {
                array![*signatures.at(i), *last.at(1)]
            } else {
                array![*last.at(0), *signatures.at(i)]
            };
    }
    last
}

pub fn expected() -> Envelope<Counter> {
    Envelope {
        seq: 9,
        transcript: 0x1e739bc13b839552e040c8adc65456cbc69b0c799669b8cb38bf6d367f016f2,
        support_turn: 6,
        last_seat: 1,
        pending: Pending { active: false, seat: 0, seq: 0, entropy: 0x0 },
        rng_heads: array![
            0xb8aa8db35de5400be60b2a9b360b72f1cd8d8f3b8da136dc408eee7c723648,
            0x3fa78d5f72cc42e13423a147b1e62d4c1691dca4642b9bfa718540cdf60b486,
        ]
            .span(),
        rng_fresh: array![false, false].span(),
        rng_referee: 0x0,
        clock: Option::None,
        outcome: Outcome { finished: true, winner: 2, reason: 1 },
        game: Counter { total: 20, next: 0, gamble: false, winner: 2, target: 20 },
    }
}

pub fn acks() -> Array<Signature> {
    array![
        Signature {
            r: 0xa12a1aab1a276b98d8e5d459967c5f563bdf8564db2be3304f32acc4d9272,
            s: 0x168b9fe03a5994abc275c6a27ff035633378885dc10c2e13a936eb8f254451d,
        },
        Signature {
            r: 0x67ab2b47c39badd9910ba954cc59e1f05e200514dc82ac56f84b5ac7bed7b39,
            s: 0x321d8430b4ff609ccca750f37f2b6123a93e2c979214739f1e20eef9b09bd00,
        },
    ]
}

pub fn timed_terms() -> Terms<Config> {
    Terms {
        chain_id: 0x534e5f54455354,
        channel: 0xc4a11e1,
        game_id: 0x2,
        prover: 0xad0b7e5,
        response_seconds: 3600,
        clock: Option::Some(
            TimeControl {
                referee: 0x6f77c2d367370dd0e65b2d4927d168eb25d33e793e2917d3eb2d7e802437929,
                settings: encode(
                    @Standard {
                        turn_ms: 30000, bank_ms: 60000, increment_ms: 2000, byoyomi: Option::None,
                    },
                ),
                rng_tip: 0x0,
            },
        ),
        players: array![0xa11ce, 0xb0b].span(),
        keys: array![
            0x2df1db011696a4657ca38f92c517c1bfb36e567f0a401334d5f793a0bd8a687,
            0x3c0b316d40d20edee780c640e08d0cf8239e08072fe0490a539554347fd2d15,
        ]
            .span(),
        rng_tips: array![
            0x13ba9cb3d0d93640c2ac9224c26501434310317b90e7076a395a28995a0f8bc,
            0x3568e68e657bca3dc139b2779a9b59a9258e15e0d9dbfe6bb6598396dcda461,
        ]
            .span(),
        config: Config { target: 20 },
    }
}

pub fn timed_steps() -> Array<Move<Action>> {
    array![
        Move::Play(Action { kind: 0, amount: 3 }),
        Move::PlayRandom(
            (
                Action { kind: 1, amount: 0 },
                0x4961f5f78d6a5776d0a0787c7ac7c53ad4858fae58d59847bbf2d5a62515155,
            ),
        ),
        Move::Reveal(0x6816196d951eb84df8af43f8cc7b82125418952b9934a12edded2b6f60e9013),
        Move::Play(Action { kind: 0, amount: 1 }), Move::Play(Action { kind: 0, amount: 1 }),
        Move::Flag,
    ]
}

/// The referee's stamp on each step.
pub fn timed_stamps() -> Array<u64> {
    array![1000000, 1040000, 1045000, 1065000, 1066000, 1160001]
}

/// The seat of each step (REFEREE for the referee's own).
pub fn timed_seats() -> Array<u8> {
    array![0, 1, 0, 0, 1, 254]
}

pub fn timed_signatures() -> Array<Signature> {
    array![
        Signature {
            r: 0x2158e0f6ee7471799b2cbf0d43cfcdf5b624100792526705826657c8f98e5d7,
            s: 0x73611a689cc7fd3a364865c0f927b7baac936f93ee5c3569c95d4967479bdd7,
        },
        Signature {
            r: 0x1b26fd7ac43d159f9a9790d1372e248753089bd7b487fffa1e6a22405a6dbd,
            s: 0xc1f4fbc4240caee446f048d4786e615572c26d209c873d6629cbf3bfdce629,
        },
        Signature {
            r: 0x7fa9e1af0dfb8b14af5a3a926b3a33b214c4515c73086462dc3ac8c6c9d9954,
            s: 0x7d7145ceb859cf64e961fa0daf9c392b93984044def5c8058e245e19bef4551,
        },
        Signature {
            r: 0x7fda2d86dd896699f12fc56573e7374c3f3f3e967573529ba171691983ce7da,
            s: 0x10cb3a14ef87b2b015571c272911ea3d1904965bb560ad56d98bb6e700aa397,
        },
        Signature {
            r: 0x51f6f4d87d2965b2002adb35a3d785c4977ea24f862bbeacefcf255cc31c811,
            s: 0xe48df3961033fc2d7208c9bd8ee01347de4bedd0e787204c6eb70d5f920ae9,
        },
        Signature { r: 0x0, s: 0x0 },
    ]
}

/// The referee's attestation after each step.
pub fn timed_attestations() -> Array<Signature> {
    array![
        Signature {
            r: 0x7ef3fed35b52aa3a3a5e1d1262655abe980d1f9d32461839ee7b8079a38bfc3,
            s: 0x4cd48ad95907d5ee446c5554a46099e80c09eae7b85698649841bde31f7fd2f,
        },
        Signature {
            r: 0x791eb47c209e5dc8b77b984494e6fa4f5f6eb00edffbd5b573f5bb129499ea3,
            s: 0x51243098f4f15f52be17ea8f7d0627a81d3654030314968a24986b0804abc5,
        },
        Signature {
            r: 0x1808dc67a9dab5b39c271b80ff991d3f152e6f4cc11a1af91e0db5c2e792bc4,
            s: 0x3e3411c4ba3fe569a41ceed5013bf8fbba07f1be7d76a0c5cb36fd5ac423f20,
        },
        Signature {
            r: 0x4f453912d81faa413f2de48f3f2027b1f46442533a5804b537532f4d7bfa7b2,
            s: 0x712d3b888b447c8502f6d456364fa3a9e381c407512292f81fe121d3d3534da,
        },
        Signature {
            r: 0x4d067be42a8d4b85e71ab2d9946a0bffbbffee91e0004adc57d0b22d5a9bfd1,
            s: 0x64a5961ce3c41f041bf0863ce87e662425a31a9528e5929f4f853bb28363e7b,
        },
        Signature {
            r: 0x29ec624eba68c9fb9e7e7cbc3888f282aebf0cd0a1ef5963ae291736a06c300,
            s: 0x2247535cf4e16bea3d9b07003b63f18c38eab26a7fa23f559953568ab2ee5e5,
        },
    ]
}

/// Each seat's last signature among steps `from..to`.
pub fn timed_finals(from: u32, to: u32) -> Array<Signature> {
    finals_of(timed_seats(), timed_signatures(), from, to)
}

pub fn timed_expected() -> Envelope<Counter> {
    Envelope {
        seq: 6,
        transcript: 0x798d52f4479223338ca4e40325c03cc180c93a605b09f3f3aa81f3b54bbe0f6,
        support_turn: 4,
        last_seat: 1,
        pending: Pending { active: false, seat: 0, seq: 0, entropy: 0x0 },
        rng_heads: array![
            0x6816196d951eb84df8af43f8cc7b82125418952b9934a12edded2b6f60e9013,
            0x4961f5f78d6a5776d0a0787c7ac7c53ad4858fae58d59847bbf2d5a62515155,
        ]
            .span(),
        rng_fresh: array![false, false].span(),
        rng_referee: 0x0,
        clock: Option::Some(
            Clock {
                seats: encode(
                    @StandardClock { banks: array![64000, 54000].span(), periods: array![].span() },
                ),
                used: 0,
                stamp: 1160001,
            },
        ),
        outcome: Outcome { finished: true, winner: 2, reason: 129 },
        game: Counter { total: 11, next: 0, gamble: false, winner: 0, target: 20 },
    }
}

pub fn byoyomi_terms() -> Terms<Config> {
    Terms {
        chain_id: 0x534e5f54455354,
        channel: 0xc4a11e1,
        game_id: 0x3,
        prover: 0xad0b7e5,
        response_seconds: 3600,
        clock: Option::Some(
            TimeControl {
                referee: 0x6f77c2d367370dd0e65b2d4927d168eb25d33e793e2917d3eb2d7e802437929,
                settings: encode(
                    @Standard {
                        turn_ms: 0,
                        bank_ms: 10000,
                        increment_ms: 0,
                        byoyomi: Option::Some(Byoyomi { periods: 3, period_ms: 5000 }),
                    },
                ),
                rng_tip: 0x0,
            },
        ),
        players: array![0xa11ce, 0xb0b].span(),
        keys: array![
            0x2df1db011696a4657ca38f92c517c1bfb36e567f0a401334d5f793a0bd8a687,
            0x3c0b316d40d20edee780c640e08d0cf8239e08072fe0490a539554347fd2d15,
        ]
            .span(),
        rng_tips: array![
            0x13ba9cb3d0d93640c2ac9224c26501434310317b90e7076a395a28995a0f8bc,
            0x3568e68e657bca3dc139b2779a9b59a9258e15e0d9dbfe6bb6598396dcda461,
        ]
            .span(),
        config: Config { target: 20 },
    }
}

pub fn byoyomi_steps() -> Array<Move<Action>> {
    array![
        Move::Play(Action { kind: 0, amount: 3 }), Move::Play(Action { kind: 0, amount: 3 }),
        Move::Play(Action { kind: 0, amount: 3 }),
        Move::PlayRandom(
            (
                Action { kind: 1, amount: 0 },
                0x4961f5f78d6a5776d0a0787c7ac7c53ad4858fae58d59847bbf2d5a62515155,
            ),
        ),
        Move::Reveal(0x6816196d951eb84df8af43f8cc7b82125418952b9934a12edded2b6f60e9013),
        Move::Play(Action { kind: 0, amount: 1 }), Move::Flag,
    ]
}

/// The referee's stamp on each step.
pub fn byoyomi_stamps() -> Array<u64> {
    array![1000000, 1012000, 1026000, 1032000, 1039000, 1042000, 1052001]
}

/// The seat of each step (REFEREE for the referee's own).
pub fn byoyomi_seats() -> Array<u8> {
    array![0, 1, 0, 1, 0, 0, 254]
}

pub fn byoyomi_signatures() -> Array<Signature> {
    array![
        Signature {
            r: 0x7cf388785aefec004c0e93f9534666667b305741a7a76f8477ae43b0e1701fc,
            s: 0x573434e44f281eb1b150bfe2154503c2e6167f7dab96e4e55fece3a28675334,
        },
        Signature {
            r: 0x54bb6ad888c0c4c62a8b7d7e9f60307dac4ea352deb5333846a5520770b02b6,
            s: 0x97fe9a2459305c7dbd5ba9bcca66d5598ff2dfe23eaf0f315e442b02df7093,
        },
        Signature {
            r: 0x3b3fa296e9056882bf36d66f09c1dd25ecdc568a9b32e464a552a72fde5b41c,
            s: 0x4e21ecc02c6115f6f7a017a398707b33d2812e43e6d9bc42ad20660c67fde50,
        },
        Signature {
            r: 0xb93d33f03de9b61d7ce06063ddf5c2c0fd197dfe88fad79592058fd748e871,
            s: 0x7c4b47268442b888518d54a273a58b58495ca132c03996c248108987e42dc26,
        },
        Signature {
            r: 0x3b6691a65a3a4ec332cc2d02e6b12d4e34b9334bf2d86cdf42641ca9243948f,
            s: 0x93cc65a5ac05c86ab20f3bebf0b3776d7404dc42f4f4cf40c4d80ee9b39bd7,
        },
        Signature {
            r: 0xbd31b8086ebeae660f0b162d94cd60d612a870a895b3603bb5af3e49713244,
            s: 0x7e1b5d35ce5e7e084000d94ee750ac0e8777a1d3075fa1af5ed90261d4364c3,
        },
        Signature { r: 0x0, s: 0x0 },
    ]
}

/// The referee's attestation after each step.
pub fn byoyomi_attestations() -> Array<Signature> {
    array![
        Signature {
            r: 0x8465de53b5cb975273c3aed331c2bad167ba310a0fa7875ec369608451e607,
            s: 0x5ea03587b2ec8e84041788d80841984b73761a7b4ff30477516bc7196f4ad8a,
        },
        Signature {
            r: 0xfe23e2aa3bc411d91bd351dc2e32a411a341ff4cf5264d007c3c19291a7652,
            s: 0x6764557209a4295b66d717f172c3e195e09e6b6658a530395b7caa6998a45ec,
        },
        Signature {
            r: 0x1d26770a94a716f32bd2f18a76550bcd1c07d52ff078cf958912d6400485f73,
            s: 0x7b03c467e2bae9a69e23311612f061807c505fd9640a68c29e07100ffaa2121,
        },
        Signature {
            r: 0x5ab32149c0c4cb80bdd9930348d9ead57b97efbfc509f5b3d3d893dabf5d318,
            s: 0x240a68b8822b73733b463ae4c4f0f1e72d878edbb625b49d274090edb282d6e,
        },
        Signature {
            r: 0x7f9199fdcc2ef3bba1242a1c700a42be8217a6cbbcf6f00ee5bec4b7d7c16ba,
            s: 0x5f6d0ee7712f0d416bc508fb6ebf9b18d16be5dbdf364f881fe99dc8f60f8fd,
        },
        Signature {
            r: 0x444b3044bf050972cc3795ddee66f3ad90e83ad9fa23c335a026cfe35cad55a,
            s: 0x7cffad3d11a65b92ebc98cbbc892878bbd5814aa75edd2dd4b8e7b9fbdd7c02,
        },
        Signature {
            r: 0x1033549c86e9f2f4b0d7215312d139fdb67f9c22cac3ed7bc7005f889c67dbd,
            s: 0x193be1649a1e7735415b71e2a5472bfb661beb561df67e5feb0c929baed1e86,
        },
    ]
}

/// Each seat's last signature among steps `from..to`.
pub fn byoyomi_finals(from: u32, to: u32) -> Array<Signature> {
    finals_of(byoyomi_seats(), byoyomi_signatures(), from, to)
}

pub fn byoyomi_expected() -> Envelope<Counter> {
    Envelope {
        seq: 7,
        transcript: 0x90e36e555b5dac714c5f485de25e78ddc854f602a444f700c9f087b0d8ba8,
        support_turn: 5,
        last_seat: 0,
        pending: Pending { active: false, seat: 0, seq: 0, entropy: 0x0 },
        rng_heads: array![
            0x6816196d951eb84df8af43f8cc7b82125418952b9934a12edded2b6f60e9013,
            0x4961f5f78d6a5776d0a0787c7ac7c53ad4858fae58d59847bbf2d5a62515155,
        ]
            .span(),
        rng_fresh: array![false, false].span(),
        rng_referee: 0x0,
        clock: Option::Some(
            Clock {
                seats: encode(
                    @StandardClock { banks: array![0, 0].span(), periods: array![2, 2].span() },
                ),
                used: 0,
                stamp: 1052001,
            },
        ),
        outcome: Outcome { finished: true, winner: 1, reason: 129 },
        game: Counter { total: 12, next: 1, gamble: false, winner: 0, target: 20 },
    }
}

pub fn hourglass_terms() -> Terms<Config> {
    Terms {
        chain_id: 0x534e5f54455354,
        channel: 0xc4a11e1,
        game_id: 0x4,
        prover: 0xad0b7e5,
        response_seconds: 3600,
        clock: Option::Some(
            TimeControl {
                referee: 0x6f77c2d367370dd0e65b2d4927d168eb25d33e793e2917d3eb2d7e802437929,
                settings: encode(@Hourglass { bank_ms: 10000 }),
                rng_tip: 0x0,
            },
        ),
        players: array![0xa11ce, 0xb0b].span(),
        keys: array![
            0x2df1db011696a4657ca38f92c517c1bfb36e567f0a401334d5f793a0bd8a687,
            0x3c0b316d40d20edee780c640e08d0cf8239e08072fe0490a539554347fd2d15,
        ]
            .span(),
        rng_tips: array![
            0x13ba9cb3d0d93640c2ac9224c26501434310317b90e7076a395a28995a0f8bc,
            0x3568e68e657bca3dc139b2779a9b59a9258e15e0d9dbfe6bb6598396dcda461,
        ]
            .span(),
        config: Config { target: 20 },
    }
}

pub fn hourglass_steps() -> Array<Move<Action>> {
    array![
        Move::Start, Move::Play(Action { kind: 0, amount: 3 }),
        Move::Play(Action { kind: 0, amount: 3 }), Move::Play(Action { kind: 0, amount: 3 }),
        Move::Play(Action { kind: 0, amount: 3 }), Move::Flag,
    ]
}

/// The referee's stamp on each step.
pub fn hourglass_stamps() -> Array<u64> {
    array![1000000, 1002000, 1006000, 1015000, 1016000, 1020001]
}

/// The seat of each step (REFEREE for the referee's own).
pub fn hourglass_seats() -> Array<u8> {
    array![254, 0, 1, 0, 1, 254]
}

pub fn hourglass_signatures() -> Array<Signature> {
    array![
        Signature { r: 0x0, s: 0x0 },
        Signature {
            r: 0x66762d2bce676d06e90b288bf0ae58d28d7e4c8c8c13d2a3792009137f67049,
            s: 0x6c09b4d537483bd0b65367de2caca132c47fab374ebc9e4441ada241141f9f7,
        },
        Signature {
            r: 0x77ebcc7dc1b0eaed3ad941c3a25d38872f69e515a5363c73acab8bd7e3ca823,
            s: 0x6aa9c0249f99a054f6e8e93d6fc76bc6656fdcc10706e7e64330f1208d551ef,
        },
        Signature {
            r: 0x4c84e8c651f008615d4a1dc8c028bbab21f10c20f7dd83b58934a989b4c5af9,
            s: 0x4d19882f5eff76a17ebae02fbb409c0f6aa8f189ebd15d2f882b3a1e8ca3179,
        },
        Signature {
            r: 0x3caded91600fb517a993cb404c89af24ba04ebcbbe6f267b7f0707cf624a173,
            s: 0xbef0bb6f70b957b08bfe37c91ed31e9c25fb3b63f223636a2f02093a423612,
        },
        Signature { r: 0x0, s: 0x0 },
    ]
}

/// The referee's attestation after each step.
pub fn hourglass_attestations() -> Array<Signature> {
    array![
        Signature {
            r: 0x7d929680fa66bd5b7f41065c87d6143b5f63c395acbe5911adeac6693501863,
            s: 0x3e03199466d3c1d79e759adc7873c20417af40d8742716c7d83f57fd2c5f0f,
        },
        Signature {
            r: 0x399d262c855e6570ed06ff6ae68ef95207328a3a1026a187aa06cbb297060f7,
            s: 0x623012e1e7e5da9413965fcbcaa9ea261896a7dc077f2d5100dd2e15225a468,
        },
        Signature {
            r: 0x35af2e9e27e1c22a40a5121397d1feb7ed8d73cbd3802f09feae4dcbbea888c,
            s: 0x5b2eacaeded88ca0dd0907247ba3682e4d94618ddedec613c1bf1ea9368f192,
        },
        Signature {
            r: 0x287c02374ca33e0057ddbc485e22b8e17973efad7a57d023a108fb70341129d,
            s: 0x4d35bd60d6ba7b7dbb3545c84df0bc270904adeeddf217d6329ef024ce0c49b,
        },
        Signature {
            r: 0x6f0aa4d76cbfdce001d8f13dfbe660765b0c9a20ddddb6ae9b532277e47cf2a,
            s: 0x59d72d69b27cf3c3f51e822b6a24256a4c1b9aee0656bced2b622887937e95a,
        },
        Signature {
            r: 0x4a633a436c06e5970351b9da59b55fee38730407baffdb4a65f6eab6d0724a0,
            s: 0x2d0dba28656ce73d11fc1265c8d2d53b79a962513083474a5150bc91d92b3fe,
        },
    ]
}

/// Each seat's last signature among steps `from..to`.
pub fn hourglass_finals(from: u32, to: u32) -> Array<Signature> {
    finals_of(hourglass_seats(), hourglass_signatures(), from, to)
}

pub fn hourglass_expected() -> Envelope<Counter> {
    Envelope {
        seq: 6,
        transcript: 0x2126a0d150a2367144711ca0c0166c1cb554259759bfb355eee2cfcaa01aba9,
        support_turn: 4,
        last_seat: 1,
        pending: Pending { active: false, seat: 0, seq: 0, entropy: 0x0 },
        rng_heads: array![
            0x13ba9cb3d0d93640c2ac9224c26501434310317b90e7076a395a28995a0f8bc,
            0x3568e68e657bca3dc139b2779a9b59a9258e15e0d9dbfe6bb6598396dcda461,
        ]
            .span(),
        rng_fresh: array![true, true].span(),
        rng_referee: 0x0,
        clock: Option::Some(
            Clock {
                seats: encode(@HourglassClock { banks: array![4000, 16000].span() }),
                used: 0,
                stamp: 1020001,
            },
        ),
        outcome: Outcome { finished: true, winner: 2, reason: 129 },
        game: Counter { total: 12, next: 0, gamble: false, winner: 0, target: 20 },
    }
}

pub fn rolled_terms() -> Terms<Config> {
    Terms {
        chain_id: 0x534e5f54455354,
        channel: 0xc4a11e1,
        game_id: 0x5,
        prover: 0xad0b7e5,
        response_seconds: 3600,
        clock: Option::Some(
            TimeControl {
                referee: 0x6f77c2d367370dd0e65b2d4927d168eb25d33e793e2917d3eb2d7e802437929,
                settings: encode(
                    @Standard {
                        turn_ms: 30000, bank_ms: 60000, increment_ms: 0, byoyomi: Option::None,
                    },
                ),
                rng_tip: 0x4703a6c3ec512c17158cfa1fd9a0df1a16b11c2fd3d23f628b3ea229348e69a,
            },
        ),
        players: array![0xa11ce, 0xb0b].span(),
        keys: array![
            0x2df1db011696a4657ca38f92c517c1bfb36e567f0a401334d5f793a0bd8a687,
            0x3c0b316d40d20edee780c640e08d0cf8239e08072fe0490a539554347fd2d15,
        ]
            .span(),
        rng_tips: array![
            0x13ba9cb3d0d93640c2ac9224c26501434310317b90e7076a395a28995a0f8bc,
            0x3568e68e657bca3dc139b2779a9b59a9258e15e0d9dbfe6bb6598396dcda461,
        ]
            .span(),
        config: Config { target: 20 },
    }
}

pub fn rolled_steps() -> Array<Move<Action>> {
    array![
        Move::Play(Action { kind: 0, amount: 3 }),
        Move::PlayRandom(
            (
                Action { kind: 1, amount: 0 },
                0x4961f5f78d6a5776d0a0787c7ac7c53ad4858fae58d59847bbf2d5a62515155,
            ),
        ),
        Move::Reveal(0xf4a89e71cd646b27bfe5b776a122a34a51b4ed5d501091e12ccad8e4e2674),
        Move::PlayRandom(
            (
                Action { kind: 1, amount: 0 },
                0x6816196d951eb84df8af43f8cc7b82125418952b9934a12edded2b6f60e9013,
            ),
        ),
        Move::Reveal(0x568d74f9d1788106145134ce74199889279234d4747001d319200a1665f5b4e),
        Move::Play(Action { kind: 0, amount: 1 }), Move::Flag,
    ]
}

/// The referee's stamp on each step.
pub fn rolled_stamps() -> Array<u64> {
    array![1000000, 1010000, 1010000, 1015000, 1015700, 1035700, 1125701]
}

/// The seat of each step (REFEREE for the referee's own).
pub fn rolled_seats() -> Array<u8> {
    array![0, 1, 254, 0, 254, 1, 254]
}

pub fn rolled_signatures() -> Array<Signature> {
    array![
        Signature {
            r: 0x15caa78f817ecb3e2a00afaeaa1ac51b9237037d45db4b1b10820acf17dceea,
            s: 0x56b3f11b9ab090d88f1b3d1e2419ca297641585e562e001351556ac92f5554a,
        },
        Signature {
            r: 0x3766244b022c3a6d18c2940c7d0fe0b6af5ef611abf7d46587e14a98ba4eb6d,
            s: 0x236e00c9860adba50b1f8f7e11fd715a1af7be1298710a76a72c3c4da70c0f,
        },
        Signature { r: 0x0, s: 0x0 },
        Signature {
            r: 0x26fa0317a0ffc067bec3347ee14f26f671e01638ff1f9589926deeb483ff80d,
            s: 0x47e6f518f0d31678dd8b99e01a6a01e00aa9ff2a9e6f15cfda362ccab04542d,
        },
        Signature { r: 0x0, s: 0x0 },
        Signature {
            r: 0x7e42626246597df6b2d209f1dbb2eefef3b936c51f027a941755b15fca031c1,
            s: 0x1b303ccc67e58c34aee6bd2d6a8c33dc987696bf91a1ea124ca0981fbf1638d,
        },
        Signature { r: 0x0, s: 0x0 },
    ]
}

/// The referee's attestation after each step.
pub fn rolled_attestations() -> Array<Signature> {
    array![
        Signature {
            r: 0x5fddc469a643cc9dac385f47af7d26e230da8b494f6a4e7859ab0fcbd15f195,
            s: 0x25c0ee9769d1464b270f98b7f2c6ea828eed73cbe999cb0aaa475b74c6f4cca,
        },
        Signature {
            r: 0x1a544c83de6b23dc3209bad980b9577a0189420784716a496247136a1a4ebd8,
            s: 0x2f0cfd880c1c5b6b03f8822fff6744b8d24a21bd54f736b4f713862bdb18e55,
        },
        Signature {
            r: 0x4ccc1273bbb6ef8e72457dd29c3fef01bedef7d97e8710b29e5e8c6fd3c29dd,
            s: 0x5924b1873b3d2c4f6966db108168d76e96e71cc1b2e28ccde39c78c54b498aa,
        },
        Signature {
            r: 0x3f33c7677e885c228d9a915a70e6b670fa9f76a3380b0e0a4aaaaa234ff7241,
            s: 0x3dd8adaeaffd9481bf58778ab864f37aa8e5e566dc0b69e59166d4336c5eadb,
        },
        Signature {
            r: 0x1697d9eded2ecb0cde51c0b13c7a2cdfabc3827dafd2d52153999d5e94424eb,
            s: 0x35ba3065e2da4cb7e556f03160ed917015a8a6f0d4f2af2c98543ed101926b5,
        },
        Signature {
            r: 0x456f31728846aebc115e6a8bca2f3a990439210160afdaef14ac62a82aa61b2,
            s: 0x541ce72c4412b36baa78142fbbbde71e261f4b001935c56a08fbb7d59e14cba,
        },
        Signature {
            r: 0x7db1d3bcf0675eb7e52c54331014a1c9a1abe4ca2e5872f0d542596315173f8,
            s: 0x7dd92844ba847617615d6efe6e0fb9ed0f8455812792565cebc8b30673a76de,
        },
    ]
}

/// Each seat's last signature among steps `from..to`.
pub fn rolled_finals(from: u32, to: u32) -> Array<Signature> {
    finals_of(rolled_seats(), rolled_signatures(), from, to)
}

pub fn rolled_expected() -> Envelope<Counter> {
    Envelope {
        seq: 7,
        transcript: 0x753dfe1db8b13fe2a26611619470581925f4b0c0d298b654f6b239df0b5cef6,
        support_turn: 4,
        last_seat: 1,
        pending: Pending { active: false, seat: 0, seq: 0, entropy: 0x0 },
        rng_heads: array![
            0x6816196d951eb84df8af43f8cc7b82125418952b9934a12edded2b6f60e9013,
            0x4961f5f78d6a5776d0a0787c7ac7c53ad4858fae58d59847bbf2d5a62515155,
        ]
            .span(),
        rng_fresh: array![false, false].span(),
        rng_referee: 0x568d74f9d1788106145134ce74199889279234d4747001d319200a1665f5b4e,
        clock: Option::Some(
            Clock {
                seats: encode(
                    @StandardClock { banks: array![60000, 60000].span(), periods: array![].span() },
                ),
                used: 0,
                stamp: 1125701,
            },
        ),
        outcome: Outcome { finished: true, winner: 2, reason: 129 },
        game: Counter { total: 12, next: 0, gamble: false, winner: 0, target: 20 },
    }
}
