[package]
name = "arbiter_counter_adapter"
version = "0.1.0"
edition = "2024_07"
cairo-version = "=2.18.0"
description = "Proof adapter for the counter game."

[dependencies]
arbiter = { path = "../../../core" }
arbiter_adapter = { path = "../../arbiter_adapter" }
arbiter_counter = { path = "../../../examples/counter" }
starknet = "=2.18.0"

[dev-dependencies]
snforge_std = "=0.63.0"
arbiter_testing = { path = "../../../testing" }

[lib]

[[target.starknet-contract]]
casm = true

[scripts]
test = "snforge test"
